### ISSUE TITLE
yarn start error

### ISSUE THREAD

**Issue by ruida** [vinbigdata-medical/vindr-lab-dashboard#1]
Hi, 

I try to build and run the vindr-lab-dashboard.   I encounter the following error message.   Where is the .env file?  Could you leave me instruction on how to work around this error message? 

Thanks, 

--Ruida 

(base) ruida@time:~/project/vindr-lab-dashboard$ yarn start
yarn run v1.22.10
$ set "PORT=3001" && env-cmd -f .env.local craco start local
Error: Failed to find .env file at path: .env.local
    at getEnvFile (/home/ruida/project/vindr-lab-dashboard/node_modules/env-cmd/dist/get-env-vars.js:40:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by HoAnhVan** [comment]
Hi @ruida 
This bug has been resolved. Please pull the latest code and retry.
